site_name: User Guide
repo_url: https://github.com/robotframework/robotframework
theme:
  name: material
  site_url: https://pekkaklarck.github.io/rf-uk-mkdocs/
  logo: robot-framework-white.png
  favicon: robot-framework.png
  icon:
    repo: fontawesome/brands/github
  features:
#    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: cyan
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: cyan
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.robotframework.org
    - icon: fontawesome/brands/github-alt
      link: https://github.com/robotframework/robotframework

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024- <a href="https://robotframework.org/foundation" target="_blank" rel="noopener">Robot Framework Foundation</a>
