site_name: Robot Framework Manual
site_description: Robot Framework is a generic open source automation framework.
site_url: https://pekkaklarck.github.io/rf-uk-mkdocs/
repo_url: https://github.com/robotframework/robotframework
edit_uri: https://github.com/pekkaklarck/rf-uk-mkdocs/blob/main/docs
copyright: |
  &copy; 2024- <a href="https://robotframework.org/foundation" target="_blank" rel="noopener">Robot Framework Foundation</a>
watch:
  - src/robot/

nav:
  - Welcome: index.md
  - Using:
    - using/index.md
    - Input data: using/data.md
    - Executing tests and tasks: using/execution.md
  - Extending:
    - extending/index.md
    - Creating libraries: extending/libraries.md
  - API:
    - api/index.md
  - Glossary: glossary.md

extra_css:
  - styles/extra.css

theme:
  name: material
  site_url: https://pekkaklarck.github.io/rf-uk-mkdocs/
  logo: styles/logo-white.png
  favicon: styles/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#00c0b5"
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          import:
            - https://docs.python.org/3/objects.inv
          inherited_members: true
          show_if_no_docstring: true
  - ezglossary:
      use_default: true
      tooltip: full
      # 'list' should give more information that 'short', but it doesn't work
      # https://github.com/realtimeprojects/mkdocs-ezglossary/issues/19
      inline_refs: short

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.robotframework.org
    - icon: fontawesome/brands/github-alt
      link: https://github.com/robotframework/robotframework

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  # PyMdown Extensions we use (there are more)
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      default_lang: python
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: robotframework
      repo: robotframework
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
