name: Generate release docs
on:
  push:
    tags:
      - 'v[0-9]*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Deploy
        run: |
          git config user.name doc-bot
          git config user.email doc@bot
          mike deploy --push --update-aliases ${{ github.ref_name }} latest
