name: Generate release docs
on:
  push:
    # Match stable versions (e.g. v7.1, v7.1.1) but not pre-releases (e.g. v7.2rc1).
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    tags:
      - 'v[0-9]*.*[0-9]'
      - '!v*[abc]*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all commits/branches.

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Get version
        # Turn tag names like 'v7.1' and 'v7.1.1' into two component version numbers like '7.1'.
        run: echo "VERSION=$(echo $GITHUB_REF_NAME | cut -c 2- | cut -d . -f 1,2 )" >> $GITHUB_ENV

      - name: Deploy
        run: |
          git config user.name doc-bot
          git config user.email doc@bot
          mike deploy --push --update-aliases ${{ env.VERSION }} latest
